spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playchat
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    #show-sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

file.dir: /Users/kycho/Desktop/upload/

backend.url: http://localhost:8080

jwt:
  header: Authorization
  #echo 'secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret'|base64
  secret: c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0Cg==
  token-validity-in-seconds: 86400